name: Check and Post Speedrun PBs

on:
  schedule:
    - cron: '0 */24 * * *'
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Run the application
      run: dotnet run
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        SPEEDRUN_USERNAME: ${{ secrets.SPEEDRUN_USERNAME }}
